# Utilise une image de base Java avec Quarkus
FROM quay.io/quarkus/quarkus-micro-image:2.0

# Définit le répertoire de travail
WORKDIR /app

# Copie l'application packagée dans le conteneur
COPY target/*-runner.jar app.jar

# Expose le port de l'API Quarkus
EXPOSE 8080

# Commande pour exécuter l'application
CMD ["java", "-jar", "app.jar"]
