global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'orders-api'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['orders-api:8080']

  - job_name: 'notification-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['notification-service:8080']

  - job_name: 'order-analytics-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['order-analytics-service:8080']

  - job_name: 'inventory-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['inventory-service:8080']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'inventory-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['inventory-service:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
      
