global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'orders-api'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['orders-api:8080']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
