# Étape de build
FROM quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:23.1.2 AS build
WORKDIR /project
COPY . .
RUN ./mvnw clean package -DskipTests

# Étape d'exécution (image minimale)
FROM quay.io/quarkus/quarkus-micro-image:2.0
WORKDIR /app
COPY --from=build /project/target/quarkus-app/lib/ /app/lib/
COPY --from=build /project/target/quarkus-app/*.jar /app/app.jar
COPY --from=build /project/target/quarkus-app/app/ /app/app/
COPY --from=build /project/target/quarkus-app/quarkus/ /app/quarkus/

EXPOSE 8080
CMD ["java", "-jar", "/app/app.jar"]
